theme: jekyll-theme-minimal
title: Alex Fu
description: The CGer.
logo: /assets/Avater.png
show_downloads: false
mail_addr: alexhuku@hotmail.com
orcid_url: https://orcid.org/0000-0001-7280-7039
twitter_url: https://twitter.com/AlexFu8304