title: Alex Fu
description: The CGer.
show_downloads: false
mail_addr: alexfu@seas.upenn.edu
orcid_url: https://orcid.org/0000-0001-7280-7039
twitter_url: https://twitter.com/AlexFu8304
linkedin_url: https://www.linkedin.com/in/alex-fu-b47b67238
institute: University of Pennsylvania
address: 3330 Walnut St, Philadelphia, PA 19104
favicon: /assets/icons/favicon.ico