title: Siyuan Fu
description: The CGer.
show_downloads: false
mail_addr: alexfu@seas.upenn.edu
orcid_url: https://orcid.org/0000-0001-7280-7039
twitter_url: https://twitter.com/AlexFu8304
linkedin_url: https://www.linkedin.com/in/alex-fu-b47b67238
# institute: Thunder Fire, Netease
# address: 599 Wangshang Rd, Binjiang District, Hangzhou, Zhejiang, China
favicon: /assets/img/icons/favicon.ico